name: kmeans
version: 0.1.0.0
github: "wgledbetter/parconc-examples"
license: BSD3

dependencies:
  - monad-par
  - vector
  - base
  - bytestring
  - binary
  - deepseq
  - array
  - time
  - random
  - parallel
  - normaldistribution

executables:
  kmeans-exe:
    main: kmeans.hs
    source-dirs: .
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
    other-modules: # Manually specify, otherwise it sees the main in GenSamples
      - KMeansCore

  kmeans-samples:
    main: GenSamples.hs
    source-dirs: .
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
    other-modules: # Manually specify, otherwise it sees the main in kmeans
      - KMeansCore
